// completion.go: shell completion and the reference table, generated from
// the registry (KS-008). `ks completion bash|zsh|fish` prints a script and
// changes nothing; installing it is the person's decision and the help
// says how. Verbs, subcommands and options complete offline from the
// schema; resource ids (sessions, jobs) complete from a local cache that a
// listing verb fills once such verbs exist (KS-021), never from a request
// made while someone is typing.
package main

import (
	"fmt"
	"sort"
	"strings"
)

// completionSpec is the registry flattened for a shell: top-level words,
// the subcommands of each group, and the options of each command.
type completionSpec struct {
	Top   []string
	Subs  map[string][]string // group -> subcommands
	Flags map[string][]string // "run" or "cruise init" -> options
}

func buildCompletionSpec(reg []*Command) completionSpec {
	spec := completionSpec{Subs: map[string][]string{}, Flags: map[string][]string{}}
	seenTop := map[string]bool{}
	globals := []string{}
	for _, f := range globalFlags {
		globals = append(globals, "--"+f.Name)
	}
	for _, c := range reg {
		head := c.Path[0]
		if !seenTop[head] {
			seenTop[head] = true
			spec.Top = append(spec.Top, head)
		}
		for _, a := range c.Aliases {
			if len(a) == 1 && !seenTop[a[0]] {
				seenTop[a[0]] = true
				spec.Top = append(spec.Top, a[0])
			}
		}
		if c.Group {
			continue
		}
		if len(c.Path) > 1 {
			spec.Subs[head] = append(spec.Subs[head], c.Path[1])
		}
		var opts []string
		for _, f := range c.Flags {
			opts = append(opts, "--"+f.Name)
			for _, al := range f.Aliases {
				opts = append(opts, "--"+al)
			}
			if f.Short != "" {
				opts = append(opts, "-"+f.Short)
			}
		}
		opts = append(opts, globals...)
		opts = append(opts, "--help")
		spec.Flags[c.Name()] = opts
		for _, a := range c.Aliases {
			spec.Flags[strings.Join(a, " ")] = opts
		}
	}
	spec.Top = append(spec.Top, "help", "completion")
	sort.Strings(spec.Top)
	return spec
}

// reg is the registry as seen at run time. The handlers in the registry's
// own initializer cannot name `registry` (an initialization cycle), so they
// read this alias, set once before anything runs.
var reg []*Command

func init() { reg = registry }

func completionScript(shell string) (string, error) {
	spec := buildCompletionSpec(reg)
	var b strings.Builder
	switch shell {
	case "bash":
		fmt.Fprintf(&b, "# ks bash completion, generated by `ks completion bash` from the command schema.\n# Install: ks completion bash > ~/.local/share/bash-completion/completions/ks (or source it from your .bashrc). ks never edits shell files.\n")
		b.WriteString("_ks_complete() {\n  local cur prev words cword\n  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n  local top=\"" + strings.Join(spec.Top, " ") + "\"\n")
		b.WriteString("  local w1=\"${COMP_WORDS[1]}\" w2=\"${COMP_WORDS[2]}\"\n  local key=\"$w1\"\n")
		b.WriteString("  case \"$w1\" in\n")
		var groups []string
		for g := range spec.Subs {
			groups = append(groups, g)
		}
		sort.Strings(groups)
		for _, g := range groups {
			subs := append([]string(nil), spec.Subs[g]...)
			sort.Strings(subs)
			fmt.Fprintf(&b, "    %s) if [ \"$COMP_CWORD\" -eq 2 ]; then COMPREPLY=($(compgen -W \"%s --help\" -- \"$cur\")); return; fi; key=\"$w1 $w2\";;\n", g, strings.Join(subs, " "))
		}
		b.WriteString("  esac\n  if [ \"$COMP_CWORD\" -eq 1 ]; then COMPREPLY=($(compgen -W \"$top\" -- \"$cur\")); return; fi\n")
		b.WriteString("  case \"$key\" in\n")
		var names []string
		for n := range spec.Flags {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			fmt.Fprintf(&b, "    \"%s\") COMPREPLY=($(compgen -W \"%s\" -- \"$cur\"));;\n", n, strings.Join(spec.Flags[n], " "))
		}
		b.WriteString("    completion) COMPREPLY=($(compgen -W \"bash zsh fish\" -- \"$cur\"));;\n  esac\n}\ncomplete -F _ks_complete ks\n")
	case "zsh":
		b.WriteString("#compdef ks\n# ks zsh completion, generated by `ks completion zsh` from the command schema.\n# Install: ks completion zsh > \"${fpath[1]}/_ks\" then restart the shell. ks never edits shell files.\n")
		b.WriteString("_ks() {\n  local -a top\n  top=(" + zshWords(spec.Top) + ")\n")
		b.WriteString("  if (( CURRENT == 2 )); then _describe 'command' top; return; fi\n  local key=\"${words[2]}\"\n")
		b.WriteString("  case \"${words[2]}\" in\n")
		var groups []string
		for g := range spec.Subs {
			groups = append(groups, g)
		}
		sort.Strings(groups)
		for _, g := range groups {
			subs := append([]string(nil), spec.Subs[g]...)
			sort.Strings(subs)
			fmt.Fprintf(&b, "    %s) if (( CURRENT == 3 )); then local -a subs; subs=(%s); _describe 'subcommand' subs; return; fi; key=\"${words[2]} ${words[3]}\";;\n", g, zshWords(subs))
		}
		b.WriteString("    completion) if (( CURRENT == 3 )); then local -a sh; sh=(bash zsh fish); _describe 'shell' sh; return; fi;;\n  esac\n  local -a opts\n  case \"$key\" in\n")
		var names []string
		for n := range spec.Flags {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			fmt.Fprintf(&b, "    \"%s\") opts=(%s);;\n", n, zshWords(spec.Flags[n]))
		}
		b.WriteString("  esac\n  (( ${#opts} )) && _describe 'option' opts\n}\n_ks \"$@\"\n")
	case "fish":
		b.WriteString("# ks fish completion, generated by `ks completion fish` from the command schema.\n# Install: ks completion fish > ~/.config/fish/completions/ks.fish. ks never edits shell files.\n")
		for _, t := range spec.Top {
			fmt.Fprintf(&b, "complete -c ks -n '__fish_use_subcommand' -a %s\n", t)
		}
		var groups []string
		for g := range spec.Subs {
			groups = append(groups, g)
		}
		sort.Strings(groups)
		for _, g := range groups {
			for _, s := range spec.Subs[g] {
				fmt.Fprintf(&b, "complete -c ks -n '__fish_seen_subcommand_from %s' -a %s\n", g, s)
			}
		}
		fmt.Fprintf(&b, "complete -c ks -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'\n")
		var names []string
		for n := range spec.Flags {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			parts := strings.Fields(n)
			cond := "__fish_seen_subcommand_from " + parts[len(parts)-1]
			for _, o := range spec.Flags[n] {
				if strings.HasPrefix(o, "--") {
					fmt.Fprintf(&b, "complete -c ks -n '%s' -l %s\n", cond, strings.TrimPrefix(o, "--"))
				} else {
					fmt.Fprintf(&b, "complete -c ks -n '%s' -s %s\n", cond, strings.TrimPrefix(o, "-"))
				}
			}
		}
	default:
		return "", fmt.Errorf("unknown shell %q; ks completion takes bash, zsh or fish", shell)
	}
	return b.String(), nil
}

func zshWords(ws []string) string {
	q := make([]string, len(ws))
	for i, w := range ws {
		q[i] = "'" + strings.ReplaceAll(w, "'", "'\\''") + "'"
	}
	return strings.Join(q, " ")
}

// referenceTable renders the command reference as Markdown from the
// schema: the same rows the docs page and the manifest carry.
func referenceTable(reg []*Command) string {
	var b strings.Builder
	b.WriteString("| command | usage | what it does | effect |\n| --- | --- | --- | --- |\n")
	for _, c := range reg {
		if c.Group {
			continue
		}
		name := "ks " + c.Name()
		if len(c.Aliases) > 0 {
			var a []string
			for _, p := range c.Aliases {
				a = append(a, strings.Join(p, " "))
			}
			name += " (" + strings.Join(a, ", ") + ")"
		}
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n", name, c.Usage(), c.Summary, c.Effects)
	}
	return b.String()
}
